### ISSUE TITLE
Pasting a long hyperlink into a complaint action prevents additional actions from being edited

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#483]
Originally reported by Scott H via Zendesk. That ticket was investigated and closed by @tom-karasch. Resolution was to delete the hyperlink from the complaint action comments.

**Comment by dougwaldron** [comment]
It was a CSS issue. Any long, unbroken string (such as a long URL) would cause the "Past Actions" table to exceed the viewport width:

![image](https://user-images.githubusercontent.com/737326/127217521-fb2cfd9d-5c7c-43fe-839f-880525965f84.png)

The CSS framework has `overflow-x: hidden;` applied to `body` (WHY???), so the table or page could not be scrolled right to access the "Edit" buttons.

Removing the `overflow-x: hidden` from `body` and also adding `word-break: break-word` to the comments column will solve the issue.

**Comment by dougwaldron** [comment]
With updated CSS:
![image](https://user-images.githubusercontent.com/737326/127218381-66706078-3f06-4907-b1a0-4e9d17caf101.png)

**Comment by tom-karasch** [comment]
Yes, I did notice that there was no horizontal scroll bar or word-wrap, which seemed odd to me. I am glad it was such an easy fix. 
Doug, if you want I can inform Scott of what the issue was, and that it is fixed.
