### ISSUE TITLE
Creating and Implementing security.txt file

### ISSUE THREAD

**Issue by romanVepd** [gaepdit/complaint-tracking#539]
Creating and implementing security policy file for CTS. Creating .well-known folder inside wwwroot of Compaint Tracking and placed security.txt inside. Also updating the ComplaintTracking c#proj file.  For more information, refer to https://github.com/gaepdit/EPD-IT/issues/68.

**Comment by dougwaldron** [comment]
Deployed to prod: https://cts.gaepd.org/.well-known/security.txt
