### ISSUE TITLE
Refresh Dev database and create separate DB migration user

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#738]
- [x] Copy the `ComplaintTracking` database from Prod into Dev.
- [x] Create separate DB accounts for `cts_app_user` with only DML rights and `cts_migrations` with DDL rights (plus select and insert).

For the DB accounts, `sbeap_app_user` and `sbeap_migrations` in the `Sbeap` database can be used for reference.

**Comment by afatima16** [comment]
@dougwaldron, we have successfully restored the CTS on Dev (104) as per your request.  Please check https://github.com/gaepdit/app-config/blob/main/sql-server-accounts.md for cts_migrations user.

**Comment by dougwaldron** [comment]
Database and users are working well. Thanks!
