### ISSUE TITLE
Refresh UAT database and create separate DB app and migration users

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#767]
Please repeat the work previously done in #738 but this time for the UAT database.

- [x] Copy the `ComplaintTracking` database from Prod into UAT.
- [x] Create separate DB accounts for `cts_app_user` with only DML rights and `cts_migrations` with DDL rights (plus select and insert).

**Comment by afatima16** [comment]
@dougwaldron I will work on it and keep you updated. Thanks!

**Comment by dougwaldron** [comment]
Data and users are working correctly. Thanks for your help!
