### ISSUE TITLE
Add City to 'My Open Complaints' section on Dashboard page

### ISSUE THREAD

**Issue by thuguley** [gaepdit/complaint-tracking#785]

**Comment by dougwaldron** [comment]
Tamika, please add the "bug" label to any issue added from the UAT. And don't assign them to me – I assign myself issue when I'm ready to work on them.

Thanks.



--

Douglas Waldron

Georgia Environmental Protection Division

(470) 524-0643 | ***@***.******@***.***>



________________________________
From: thuguley ***@***.***>
Sent: Friday, May 31, 2024 2:20 PM
To: gaepdit/complaint-tracking ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gaepdit/complaint-tracking] Add City to 'My Open Complaints (Issue #785)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
