### ISSUE TITLE
Create separate migration user for Prod DB

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/complaint-tracking#800]
Please create separate DB accounts on the production "ComplaintTracking" database for `cts_app_user` with only DML rights and `cts_migrations` with DDL rights (plus select and insert). The changes should be the same as what was recently done on Dev (#738) and UAT (#767). Please keep the password for `cts_app_user` unchanged.

**Comment by afatima16** [comment]
@dougwaldron requested is completed. Please verify at your connivence. 
for cts_migrations password https://github.com/gaepdit/app-config/blob/main/sql-server-accounts.md

**Comment by dougwaldron** [comment]
Everything looks good 👍🏼
